spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/myspringboot?characterEncoding=utf-8
    username: root
    password:

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

mybatis:
  mapper-locations: classpath:mapper/*.xml # sql映射文件位置
  configuration: # 指定mybatis全局配置文件中的相关配置项
    map-underscore-to-camel-case: true

pagehelper:
  # 分页合理化参数，默认值为false。当该参数设置为 true 时，pageNum<=0 时会查询第一页， pageNum>pages（超过总数时），会查询最后一页
  reasonable: true